### ISSUE TITLE
Error on startup, followed by being stuck at initialization stage

### ISSUE THREAD

**Issue by Griefed** [Griefed/docker-D-Zone#2]
An update to d-zone seems to have borked the docker image. 

```
[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 50-config: executing... 
[cont-init.d] 50-config: exited 0.
[cont-init.d] 99-custom-files: executing... 
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-files: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
npm ERR! code EACCES
npm ERR! syscall scandir
npm ERR! path /root/.npm/_logs
npm ERR! errno -13
npm ERR! Your cache folder contains root-owned files, due to a bug in
npm ERR! previous versions of npm which has since been addressed.
npm ERR! To permanently fix this problem, please run:
npm ERR!   sudo chown -R 1003:998 "/root/.npm"
glob error [Error: EACCES: permission denied, scandir '/root/.npm/_logs'] {
  errno: -13,
  code: 'EACCES',
  syscall: 'scandir',
  path: '/root/.npm/_logs'
}
> d-zone@0.1.67 start /app/d-zone
> node index.js
Initializing server
Bot disconnected, reconnecting...
Bot disconnected, reconnecting...
2020-11-02T10:55:44.419Z Logged in as: xxxxxx
Connected to 1 server(s)
Websocket listening on port 3000
TypeError: Cannot read property 'add' of undefined
    at Shard.wsEvent (/app/d-zone/node_modules/eris/lib/gateway/Shard.js:421:65)
    at Shard.onWSMessage (/app/d-zone/node_modules/eris/lib/gateway/Shard.js:1727:26)
    at WebSocket.ws.onmessage (/app/d-zone/node_modules/eris/lib/gateway/Shard.js:1605:33)
    at WebSocket.onMessage (/app/d-zone/node_modules/eris/node_modules/ws/lib/event-target.js:120:16)
    at WebSocket.emit (events.js:315:20)
    at Receiver.receiverOnMessage (/app/d-zone/node_modules/eris/node_modules/ws/lib/websocket.js:719:20)
    at Receiver.emit (events.js:315:20)
    at Receiver.dataMessage (/app/d-zone/node_modules/eris/node_modules/ws/lib/receiver.js:414:14)
    at Receiver.getData (/app/d-zone/node_modules/eris/node_modules/ws/lib/receiver.js:346:17)
    at Receiver.startLoop (/app/d-zone/node_modules/eris/node_modules/ws/lib/receiver.js:133:22)
TypeError: Cannot read property 'get' of undefined
    at Shard.wsEvent (/app/d-zone/node_modules/eris/lib/gateway/Shard.js:432:50)
    at Shard.onWSMessage (/app/d-zone/node_modules/eris/lib/gateway/Shard.js:1727:26)
    at WebSocket.ws.onmessage (/app/d-zone/node_modules/eris/lib/gateway/Shard.js:1605:33)
    at WebSocket.onMessage (/app/d-zone/node_modules/eris/node_modules/ws/lib/event-target.js:120:16)
    at WebSocket.emit (events.js:315:20)
    at Receiver.receiverOnMessage (/app/d-zone/node_modules/eris/node_modules/ws/lib/websocket.js:719:20)
    at Receiver.emit (events.js:315:20)
    at Receiver.dataMessage (/app/d-zone/node_modules/eris/node_modules/ws/lib/receiver.js:414:14)
    at Receiver.getData (/app/d-zone/node_modules/eris/node_modules/ws/lib/receiver.js:346:17)
    at Receiver.startLoop (/app/d-zone/node_modules/eris/node_modules/ws/lib/receiver.js:133:22)
11/2 5:50:53 PM client connected to server (1 total)
```

Possibly related to https://github.com/d-zone-org/d-zone/pull/237#event-3946151197

**Comment by Griefed** [comment]
Created [d-zone/master](https://github.com/Griefed/docker-D-Zone/tree/d-zone/master)-branch to test whether the master branch of D-Zone throws the same error. If the master branch and the new Dockerfile work, it would also lead to a more customized experience with D-Zone, as the new one passes password, url, token, server id and whether to hide offline users.

**Comment by Griefed** [comment]
Seemed to be related to the priviledged intents thing in the discord bot settings. 
If you are experiencing the same problem, make sure you've set up your bot correctly:

![image](https://user-images.githubusercontent.com/44273438/100787187-8d9f9180-3413-11eb-8616-08f8ee7d890f.png)
